### ISSUE TITLE
Unable to mount SMB share

### ISSUE THREAD

**Issue by jarrodCoombes** [jamf/JamfSync#49]
Pretty much as the title says, I am not able to mount the share, which is a local SMB share. I am absolutely sure I am using the correct password, though it is very unclear what username it is using (I assume the same one specified in Jamf?).

`24/12/02 09:06:02-ERROR: Failed to load the JAMF Distribution Point (<server>) (JSS) distribution point: mountingFailed`

Is there a way to get a more verbose log output to work out what is going in here?

**Comment by nfawad227** [comment]
I'm experiencing the same issue can't mount the share drive

**Comment by BIG-RAT** [comment]
Version of Jamf Sync being used?
The account used is the Read/Write account for the file share distribution point (File Sharing tab).
Any other SMB shares mounted when you launch Jamf Sync?

**Comment by jarrodCoombes** [comment]
Hi @BIG-RAT I am using the latest version, 1.4.0, but it was an issue on previous versions as well. Yes, the account in question is the Read/Write account specified in the Jamf settings (it's also specified as the read only account if that makes a difference), and no, I have no other SMB shared mounted when I launch Jamf Sync.

**Comment by BIG-RAT** [comment]
I've not encountered any issues having & in the password. Have you tried clearing out the keychain entry for that share (search for JamfSync). Throw in a reboot as well to get a clean start.

**Comment by jarrodCoombes** [comment]
Keychain has been cleaned, several times. I don't save the password while trying to get this work now. The problem seems to exist on multiple machines, but persists across reboots.

Is there a way to get a verbose log on this? The error thrown by the app is not very helpful.

**Comment by BIG-RAT** [comment]
log stream is available. See if the following helps:
`log stream --debug --predicate 'subsystem == "com.jamf.jamfsync"'`

Also, verify the following in Privacy & Security -> Files & Folders
<img width="468" alt="image" src="https://github.com/user-attachments/assets/22dce09c-9971-498a-8ee7-1aeb45729dc3">

**Comment by jarrodCoombes** [comment]
The only thing that come out of the log stream is the exact same error I see in the app, which is way to generic to be of any help (`Failed to load the JAMF Distribution Point (<SMB_SERVER>) (JSS) distribution point: mountingFailed`) Is there a related log I can monitor to see what the actual issue is?

With regards to the security, I do not see JamfSync in that list at all, but there does not appear to be a way to add it. So how do I make sure it has access to network volumes?

**Comment by BIG-RAT** [comment]
I'd remove the config profile.
Run the following:
`sudo tccutil reset All com.jamf.jamfsync`
Next time you launch Jamf Sync and select a network share you should get the prompt to allow access to files on a network volume.

**Comment by jarrodCoombes** [comment]
So I fixed it. The problem was the setting in Jamf, specifically the "Share name" was wrong, it had a `\` in it. I removed it on a whim, and the issue was resolved.

I would highly recommend adding some sort of debug, verbose logging for share mounting. If I had been able to see exactly what Jamf Sync was trying to mount, I'd probably have been able to fix this months ago. Simply throwing a `mountFailed` is really not helpful at all.

**Comment by BIG-RAT** [comment]
debug logging - noted.
Glad you got it figured out.

**Comment by ajrich77** [comment]
I am having the mounting failed error with two different accounts and both passwords are correct. Version is 1.4.0. When I test the credentials they succeed and the password is saved in keychain but the prompt still occurs each time I attempt to synchronize to Jamf server; JamfSync sees the files in the destination but fails to mount:
<img width="1012" alt="Screenshot 2024-12-10 at 6 23 12 PM" src="https://github.com/user-attachments/assets/0841122d-98f9-4df2-b755-a04de95a0c89">
<img width="1012" alt="Screenshot 2024-12-10 at 6 24 02 PM" src="https://github.com/user-attachments/assets/54cc588b-7498-4419-8428-f233163368c3">

<img width="1012" alt="Screenshot 2024-12-10 at 6 24 30 PM" src="https://github.com/user-attachments/assets/278451ec-b0fd-4d0a-a986-9d00c547f7c0">

**Comment by BIG-RAT** [comment]
Are you using the read/write account that is set in Jamf Pro?

**Comment by HarryStrandJamf** [comment]
This has may have been solved with version 1.5.0. Please comment whether this is the case or not.

**Comment by homeworkcnm** [comment]
> This has may have been solved with version 1.5.0. Please comment whether this is the case or not.

I‘m using version 1.5.1 now and still facing this issue, cannot figure out the reason. Since in the morning everything works fine, I was syncing packages from jsdc to dp successfully but suddenly, almost every package un-synced failed and I'm not able to mount my dp anymore.

**Comment by dougnayes** [comment]
Hi, I am running into this issue. I have verified I am using the right account for the distro point.  I am using version 1.5.1 for Jamf Sync

**Comment by ajrich77** [comment]
The same thing is occurring again on multiple computers running 1.5.1. Additionally it defaults to an account that was used for testing but is not the account used on a regular basis. Is there a best practice for completely uninstalling or removing all stored settings/accounts?

**Comment by dougnayes** [comment]
> The same thing is occurring again on multiple computers running 1.5.1. Additionally it defaults to an account that was used for testing but is not the account used on a regular basis. Is there a best practice for completely uninstalling or removing all stored settings/accounts?

I was able to resolve this. I noticed the the smb share was still mounted in my finder even when Sync was not launched.  to get Sync to work again I just had to unmount the smb from my finder and relaunch the application. I'm not sure it's the exact same issue you are having, but it's worth checking.

**Comment by cdenesha** [comment]
> I was able to resolve this. I noticed the the smb share was still mounted in my finder even when Sync was not launched. to get Sync to work again I just had to unmount the smb from my finder and relaunch the application.

@dougnayes Bingo!! I had it today, and I had the share on the other server mounted to rename the old packages as I keep them around for awhile. Thank You for your noticing, and for informing us!!

chris :)
